### ISSUE TITLE
force dark theme through resistFingerprinting

### ISSUE THREAD

**Issue by alexmo1997** [rugk/website-dark-mode-switcher#48] opened 2022-01-04 00:01 UTC
I really like using the firefox pref `privacy.resistFingerprinting`, which enhances privacy a lot, but also blocks `ui.systemUsesDarkTheme` and `browserSettings.overrideContentColorScheme`.

I'd like to make an exception in this case though, as browsing with a dark theme is more important to me than one bit of information for possible trackers.

This used to be possible with this extension in its `v1` architecture (which did some js tricks I guess), but obviously doesn't work anymore as of the use of `overrideContentColorScheme`.

So it would be awesome if there was a way to enable the old method of setting the color-scheme, so you could force `prefers-color-scheme: dark` and still have `privacy.resistFingerprinting` with its bunch of other features.

**Comment by rugk** [comment] 2022-01-04 11:02
Duplicate of https://github.com/rugk/website-dark-mode-switcher/issues/22

**Closed by rugk** 2022-01-04 11:02 UTC
Labels: enhancement

**Comment by rugk** [comment] 2022-01-04 11:08
Hi and thanks for your report. This is actually a known issue.
So [please have a look here](https://github.com/rugk/website-dark-mode-switcher/issues/22#issuecomment-988387763). The TL;DR is: You can use the old v1 extension version if you are in need of that feature. Unfortunately, as you correctly said, with the new API that is not currently possible, and is a limitation of Firefox we cannot influence.
However, I am also reluctant to include the old code there, not only because of the technical complexity, also because it generally was an ugly hack/workaround, I'd not like to go back.

So the currently suggested workaround is, unfortunately, to install a v1 version of the extension and disable auto-updates. There is not much I can do here, I'm afraid.

Also notice that the v1 way _may_ be detectable by websites, i.e. websites _may_ be able to detect that you are using this extension, although we did everything to prevent this, it cannot be 100%ly eliminated. So privacy-wise, this is also a double-edged sword.

**Comment by alexmo1997** [comment] 2022-01-04 17:35
Oh, somehow I couldn't find that with the GitHub search.

Well, that's unfortunate.
I can understand why you don't wanna include the old hack though, thanks for the consideration anyway. I'm gonna use v1 for now then.
