### ISSUE TITLE
Support setting light/dark mode on a per site/URL basis.

### ISSUE THREAD

**Issue by vamega** [rugk/website-dark-mode-switcher#55] opened 2023-05-30 21:17 UTC
## Background
My system preference is set to use dark mode.
I browse some websites where their dark mode theme makes the content barely legible.
I use the extension to switch those website to use light mode (the websites in question use media queries, so forcing light mode works).

However this addon currently switches this preference across all sites in my browser.

## Proposed solution
Allow associating this preference on a per-site basis.

## Alternatives
Continue to toggle this on a per site basis.

## Additional context
I'm unsure if the `overrideContentColorScheme` API allows changes like this to be isolated to a website. A quick scan of the code made me aware that this was the API that was being used to change the result of the media query `prefers-color-scheme`.

I was originally hoping to do this via Stylus, since it has the ability to set styles on a per site/per url basis, but couldn't find a way to change the result of the media query. This addon lets me change the result of the media-query, but applies that globally.

**Comment by rugk** [comment] 2023-05-31 14:03
Thanks for your elaborate request. Yeah as you correctly noticed your feature request is hard to implement unfortunately. Actually this is a duplicate of https://github.com/rugk/website-dark-mode-switcher/issues/12, there it is [also explained](https://github.com/rugk/website-dark-mode-switcher/issues/12#issuecomment-1039470062) that the API is global, and AFAIK this has not changed until now, so there is nothing I can do.

What you could do or also work upon is using the old [v1.3 version](https://github.com/rugk/website-dark-mode-switcher/releases/tag/v1.3), which does what you basically wanted to do with Stylus. However, overriding that media query is way harder than you may think (feel free to look though the code and PRs by contributors) and ends up being quite unreliable, so for now I prefer to stick and use the Firefox API.
More information about that history in the [latest release notes for v2.0](https://github.com/rugk/website-dark-mode-switcher/releases/tag/v2.0).

**Comment by rugk** [comment] 2023-05-31 14:07
Duplicate of #12

**Closed by rugk** 2023-05-31 14:07 UTC
Labels: enhancement

**Comment by vamega** [comment] 2023-05-31 17:17
Thanks so much for such a detailed response!
